name: flutter_screen_capture_example
description: Demonstrates how to use the flutter_screen_capture plugin.

publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screen_capture:
    path: ../

  screen_retriever: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true