name: flutter_screen_capture
description: A plugin to capture the entire screen or part of it on desktop platforms.
version: 1.0.2
repository: https://github.com/albemala/flutter_screen_capture

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^3.2.2
  screen_retriever: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterScreenCapturePlugin
      macos:
        pluginClass: FlutterScreenCapturePlugin
      windows:
        pluginClass: FlutterScreenCapturePluginCApi
