name: flutter_screen_capture
description: A plugin to capture the entire screen or part of it on desktop platforms.
version: 1.0.2
repository: https://github.com/albemala/flutter_screen_capture

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^3.2.0
  screen_retriever: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.0.1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterScreenCapturePlugin
      macos:
        pluginClass: FlutterScreenCapturePlugin
      windows:
        pluginClass: FlutterScreenCapturePluginCApi
